export const LOAD_ALL_CURRENCIES = 'LOAD_ALL_CURRENCIES'
export const LOAD_CURRENCY_BY_ID = 'LOAD_CURRENCY_BY_ID'
export const LOAD_LOCATION_SEARCH = 'LOAD_LOCATION_SEARCH'
export const LOAD_WEATHER_LOCATION = 'LOAD_WEATHER_LOCATION'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'